/**
 * 当 JSON 食材数据加载失败或为空时使用的兜底食材数据
 * 仅用于防止页面完全空白，方便体验和调试
 */
export function getFallbackIngredients(): Array<{
  name: string;
  category: string;
  selected: boolean;
}> {
  return [
    { name: '鸡胸肉', category: 'meat', selected: false },
    { name: '鸡腿', category: 'meat', selected: false },
    { name: '鸡翅', category: 'meat', selected: false },
    { name: '鸡里脊', category: 'meat', selected: false },
    { name: '猪肉', category: 'meat', selected: false },
    { name: '五花肉', category: 'meat', selected: false },
    { name: '梅花肉', category: 'meat', selected: false },
    { name: '牛肉', category: 'meat', selected: false },
    { name: '牛腩', category: 'meat', selected: false },
    { name: '排骨', category: 'meat', selected: false },
    { name: '牛排', category: 'meat', selected: false },
    { name: '培根', category: 'meat', selected: false },
    { name: '火腿肠', category: 'meat', selected: false },

    { name: '虾仁', category: 'seafood', selected: false },
    { name: '大虾', category: 'seafood', selected: false },
    { name: '鱼片', category: 'seafood', selected: false },
    { name: '带鱼', category: 'seafood', selected: false },
    { name: '鲈鱼', category: 'seafood', selected: false },
    { name: '三文鱼', category: 'seafood', selected: false },
    { name: '花蛤', category: 'seafood', selected: false },
    { name: '鱿鱼', category: 'seafood', selected: false },

    { name: '鸡蛋', category: 'egg_dairy', selected: false },
    { name: '咸鸭蛋', category: 'egg_dairy', selected: false },
    { name: '鹌鹑蛋', category: 'egg_dairy', selected: false },
    { name: '牛奶', category: 'egg_dairy', selected: false },
    { name: '酸奶', category: 'egg_dairy', selected: false },
    { name: '芝士', category: 'egg_dairy', selected: false },

    { name: '西兰花', category: 'vegetable', selected: false },
    { name: '番茄', category: 'vegetable', selected: false },
    { name: '西红柿', category: 'vegetable', selected: false },
    { name: '土豆', category: 'vegetable', selected: false },
    { name: '胡萝卜', category: 'vegetable', selected: false },
    { name: '白萝卜', category: 'vegetable', selected: false },
    { name: '黄瓜', category: 'vegetable', selected: false },
    { name: '生菜', category: 'vegetable', selected: false },
    { name: '油麦菜', category: 'vegetable', selected: false },
    { name: '菠菜', category: 'vegetable', selected: false },
    { name: '小白菜', category: 'vegetable', selected: false },
    { name: '青椒', category: 'vegetable', selected: false },
    { name: '红椒', category: 'vegetable', selected: false },
    { name: '彩椒', category: 'vegetable', selected: false },
    { name: '洋葱', category: 'vegetable', selected: false },
    { name: '大葱', category: 'vegetable', selected: false },
    { name: '西葫芦', category: 'vegetable', selected: false },
    { name: '茄子', category: 'vegetable', selected: false },
    { name: '豆角', category: 'vegetable', selected: false },
    { name: '四季豆', category: 'vegetable', selected: false },
    { name: '芹菜', category: 'vegetable', selected: false },
    { name: '莲藕', category: 'vegetable', selected: false },
    { name: '南瓜', category: 'vegetable', selected: false },
    { name: '山药', category: 'vegetable', selected: false },
    { name: '香菜', category: 'vegetable', selected: false },

    { name: '香菇', category: 'fungus', selected: false },
    { name: '金针菇', category: 'fungus', selected: false },
    { name: '杏鲍菇', category: 'fungus', selected: false },
    { name: '平菇', category: 'fungus', selected: false },
    { name: '木耳', category: 'fungus', selected: false },

    { name: '豆腐', category: 'soy', selected: false },
    { name: '老豆腐', category: 'soy', selected: false },
    { name: '嫩豆腐', category: 'soy', selected: false },
    { name: '豆干', category: 'soy', selected: false },
    { name: '腐竹', category: 'soy', selected: false },

    { name: '大米', category: 'staple', selected: false },
    { name: '糯米', category: 'staple', selected: false },
    { name: '挂面', category: 'staple', selected: false },
    { name: '米粉', category: 'staple', selected: false },
    { name: '粉丝', category: 'staple', selected: false },
    { name: '馒头', category: 'staple', selected: false },
    { name: '面包', category: 'staple', selected: false },
    { name: '吐司', category: 'staple', selected: false },

    { name: '蒜瓣', category: 'seasoning', selected: false },
    { name: '姜', category: 'seasoning', selected: false },
    { name: '葱花', category: 'seasoning', selected: false },
    { name: '干辣椒', category: 'seasoning', selected: false },
    { name: '青椒圈', category: 'seasoning', selected: false },
    { name: '花椒', category: 'seasoning', selected: false },
    { name: '八角', category: 'seasoning', selected: false },
    { name: '桂皮', category: 'seasoning', selected: false },
    { name: '香叶', category: 'seasoning', selected: false },
    { name: '酱油', category: 'seasoning', selected: false },
    { name: '生抽', category: 'seasoning', selected: false },
    { name: '老抽', category: 'seasoning', selected: false },
    { name: '蚝油', category: 'seasoning', selected: false },
    { name: '香油', category: 'seasoning', selected: false },
    { name: '料酒', category: 'seasoning', selected: false },
    { name: '白胡椒粉', category: 'seasoning', selected: false },
    { name: '黑胡椒', category: 'seasoning', selected: false },
    { name: '香醋', category: 'seasoning', selected: false },
    { name: '陈醋', category: 'seasoning', selected: false },

    { name: '菠萝', category: 'fruit', selected: false },
    { name: '芒果', category: 'fruit', selected: false },
    { name: '木瓜', category: 'fruit', selected: false },
    { name: '牛油果', category: 'fruit', selected: false },
    { name: '百香果', category: 'fruit', selected: false },
    { name: '蓝莓', category: 'fruit', selected: false },
    { name: '香蕉', category: 'fruit', selected: false },
    { name: '柠檬', category: 'fruit', selected: false },
    { name: '西柚', category: 'fruit', selected: false },

    { name: '栗子', category: 'nut', selected: false },
    { name: '花生', category: 'nut', selected: false },
    { name: '花生米', category: 'nut', selected: false },
    { name: '腰果', category: 'nut', selected: false },
    { name: '核桃', category: 'nut', selected: false },
    { name: '芝麻', category: 'nut', selected: false },
    { name: '黑芝麻', category: 'nut', selected: false },
    { name: '白芝麻', category: 'nut', selected: false },

    { name: '枸杞', category: 'medicinal', selected: false },
    { name: '桂圆', category: 'medicinal', selected: false },
    { name: '红枣', category: 'medicinal', selected: false },
    { name: '乌梅', category: 'medicinal', selected: false },
    { name: '山楂干', category: 'medicinal', selected: false },
    { name: '桂花', category: 'medicinal', selected: false },
    { name: '银耳', category: 'medicinal', selected: false },
    { name: '百合', category: 'medicinal', selected: false },
    { name: '黄芪', category: 'medicinal', selected: false },
    { name: '桃胶', category: 'medicinal', selected: false },
    { name: '皂角米', category: 'medicinal', selected: false },
    { name: '花胶', category: 'medicinal', selected: false },

    { name: '西米', category: 'other', selected: false },
    { name: '椰奶', category: 'other', selected: false },
    { name: '巧克力', category: 'other', selected: false },
    { name: '巧克力豆', category: 'other', selected: false },
    { name: '红豆沙', category: 'other', selected: false },
    { name: '浓缩咖啡', category: 'other', selected: false },
    { name: '冰块', category: 'other', selected: false },
    { name: '高汤', category: 'other', selected: false }
  ];
}

